theme: jekyll-theme-cayman
title: Enterprise Solution Architect @ IBM (Watsonx Data Labs)
description: Systems thinker — distributed systems, enterprise architecture, and GenAI. I design and build scalable, clean solutions that prioritize real-world impact and people.

# SEO Settings
plugins:
  - jekyll-seo-tag

author: Pravin Bhat
url: https://pravinbhat.github.io

# Social Media
twitter:
  username: pravinbhat
  card: summary_large_image

social:
  name: Pravin Bhat
  links:
    - https://github.com/pravinbhat
    - https://linkedin.com/in/pravinbhat

# SEO Defaults
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/og-default.jpg
      author: Pravin Bhat
